### ISSUE TITLE
Exception when deleting a branch

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/droid#64]
I'm running the latest version of `master` locally. When I try to delete a branch, it is not removed and I get the following exception in the terminal:
```
java.lang.Exception: Error removing image: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

	at droid.command$remove_container.invokeStatic(command.clj:68)
	at droid.command$remove_container.invoke(command.clj:60)
	at droid.branches$delete_local_branch.invokeStatic(branches.clj:263)
	at droid.branches$delete_local_branch.invoke(branches.clj:259)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2039)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Agent$Action.doRun(Agent.java:114)
	at clojure.lang.Agent$Action.run(Agent.java:163)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I mentioned this in #50 but I want to keep this separate from the `make clean` request.

**Comment by jamesaoverton** [comment]
Yeah, sounds like a bug.

**Comment by jamesaoverton** [comment]
The Docker stuff has been substantially reworked. I'm going to close this, but please reopen if you see the issue again.
